name: goreleaser

on:
  workflow_dispatch:
    inputs:
        version:
            description: 'Version to release'
            required: true
            default: 'v0.0.0'

  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'
          cache: true

      - name: Create tag
        run: git tag ${{ github.event.inputs.version }}
        if: github.event_name == 'workflow_dispatch'

      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
